import AIEElement from './AIEElement';
import AIEAbstractMaduration from './AIEAbstractMaduration';
import AIEAbstractMutation from './AIEAbstractMutation';
export default abstract class AIE {
    private eventProcessor;
    private environment;
    private name;
    private context;
    private cycles;
    private maxUpdateCycles;
    private pregnancyCalculator;
    constructor(name: string, context: any);
    addCycle(): void;
    getCycles(): number;
    setMaxUpdatedCycles(max: any): void;
    getMaxUpdatedCycles(): number;
    abstract getPregnancySpeed(): number;
    abstract getMutation(): AIEAbstractMutation;
    abstract getMaduration(): AIEAbstractMaduration;
    abstract getElements(): NodeListOf<any>;
    registerEvent(event: string, func: any): void;
    private createTree;
    private getParentNode;
    getName(): string;
    private createEnvironment;
    private updatePregnancyTree;
    private initializeElements;
    start(): void;
    getState(): any;
    setState(value: any, child?: AIEElement): void;
    getContext(): any;
    mutate(): void;
    updatePregnancy(): void;
    private getElementState;
    abstract createElement(el: any): AIEElement;
}
