import AIEMemory from './AIEMemory';
import AIEEventProcessor from './AIEEventProcessor';
import AIEPregnancyCalculator from './AIEPregnancyCalculator';
import AIEProperty from './AIEProperty';
export default abstract class AIEElement {
    private trigger;
    protected baseElement: any;
    private name;
    private children;
    private processor;
    private parent;
    private memory;
    private onChangeTrigger;
    private pregnancy;
    private pregnancyCalculator;
    private maxPregnancy;
    private pregnancyBase;
    private freePregnancy;
    private updates;
    private maxUpdates;
    private born;
    private properties;
    constructor(baseElement: any);
    setUpdates(updates: number): void;
    setMaxPregnancy(pregnancy: number): void;
    setName(name: string): void;
    generateId(): string;
    updatePregnancy(): void;
    getInteractions(): number;
    getEnvInteractions(): number;
    getName(): string;
    getTriggersName(): any;
    getEventName(): string;
    getPregnancyIncrement(): number;
    isAmbient(): boolean;
    setParent(element: AIEElement): void;
    setProccesor(processor: AIEEventProcessor): void;
    getParent(): AIEElement;
    setProperties(properties: Array<AIEProperty>): void;
    setOnChangeTrigger(trigger: string): void;
    hasOnChangeTrigger(): boolean;
    runOnChangeTrigger(): boolean;
    getProperties(): Array<AIEProperty>;
    getPropertiesNames(): Array<String>;
    setChildren(element: AIEElement): void;
    private removeChild;
    onTrigger(name: string): void;
    getChildren(): AIEElement[];
    incrementScore(): void;
    getScore(): number;
    updateChildrenPregnancy(): void;
    getMaxAmbientPregnancy(): number;
    getTotalAmbientPregnancy(): number;
    getMaxAmbientPropertyValue(name: string): number;
    getProperty(nameProp: string): AIEProperty;
    getChildPropertyValue(nameProp: string, childName: string): number;
    getChildPropertyMaxValue(nameProp: string, childName: string): number;
    getPercentualPregnancy(): number;
    hasParent(): boolean;
    hasChildren(): boolean;
    setPregnancyCalculator(pregnancyCalculator: AIEPregnancyCalculator): void;
    getPregnancy(): number;
    setScore(value: number): number;
    setPregnancy(value: number): void;
    getTotalPregnancy(): number;
    setFreePregnancy(free: number): void;
    getFreePregnancy(): number;
    mutate(): void;
    private recalculatePregnancyAfterMutation;
    abstract initializeMemory(seed: string): AIEMemory;
    abstract setBaseElement(baseElement: any): void;
    abstract getAttr(attributeName: string): string;
    abstract getAttrs(attributeName: string): any;
    abstract getBaseElementParent(): Node;
    abstract getBaseElement(): any;
    abstract bindTriggers(): void;
    abstract getPhysicalAttributes(): any;
    abstract transform(): void;
}
